### ISSUE TITLE
docker compose command error

### ISSUE THREAD

**Issue by fpsilva-source** [cisagov/decider#27]
Hello,

I am not able to start, below is the error screen that generates when executing the command according to the documentation.

![image](https://user-images.githubusercontent.com/75707870/226124226-d2dedb72-fe54-495d-9365-8094ee0b8d74.png)

**Comment by damionmounts** [comment]
Hello!
Apologies for getting to this a little late.

`WEB_PORT` not being set leads me to believe .env doesn't exist.
- Try `cp .env.example .env` before running `compose up`
- Or, if that was already done, please show the contents of your .env file (hiding passwords of course)

**Comment by fpsilva-source** [comment]
Hello,
@damionmounts 

![image](https://user-images.githubusercontent.com/75707870/226923623-da886808-9cac-45b0-a16e-2149f94bff51.png)

**Comment by fpsilva-source** [comment]
@damionmounts 

This image print correct.

![image](https://user-images.githubusercontent.com/75707870/226924465-fdd77dd0-37e4-4815-95b5-47e66d7fe213.png)

**Comment by damionmounts** [comment]
That's the one!

I do see a trailing W on `WEB_IP=127.0.0.1` that should be removed at least.

**Comment by damionmounts** [comment]
That looks like Windows Terminal if I'm not mistaken -

I'm unsure how picky Docker is with it - but putting your .env through dos2unix may fix issues with line-endings (if that is the culprit).

**Comment by fpsilva-source** [comment]
@damionmounts 

The error still persists with the removal of the W.


![image](https://user-images.githubusercontent.com/75707870/226991322-d9fb756c-2e33-42f5-a345-f7611134d8f5.png)

**Comment by damionmounts** [comment]
That did fix the `WEB_PORT` not being defined though!

The other issue appears to be related to your Docker version
(as per some browsing: https://stackoverflow.com/questions/66514436/difference-between-docker-compose-and-docker-compose)

`docker-compose` is the old way to call it, and `docker compose` is the new way.
The new way hadn't worked for you.
It is likely that the structure of the yaml is not accepted by the older version.

Current Suggestion: **_Update Docker_**

**Comment by fpsilva-source** [comment]
@damionmounts 

![image](https://user-images.githubusercontent.com/75707870/227003869-267d7c40-2dea-414a-82f4-e9bcd494717b.png)

**Comment by damionmounts** [comment]
### You'll need to update your installation
https://docs.docker.com/compose/install/

You appear to have Compose V1, which cannot read the compose.yaml file in the repo.
Compose V1 is unsupported soon as well.

![image](https://user-images.githubusercontent.com/31434109/227018170-cc771892-bf10-40af-8d07-d2fe5e03266d.png)

**Comment by fpsilva-source** [comment]
@damionmounts ,

Hello,

I managed to improve with your tips. Another point I came across is regarding the configuration of a public IP. In the .env file, when I change the IP from localhost to my public IP, the application gives an error, then I need to go back to localhost so that the application starts as shown in the image below. What changes do I need to make to enter a public IP?


![image](https://user-images.githubusercontent.com/75707870/227785382-2a62a127-cdf4-4c7e-bcf4-a9ca3c93956b.png)

**Comment by damionmounts** [comment]
Hello @fpsilva-source,

Setting `WEB_IP=0.0.0.0` in your .env will cause Decider (via Docker) to bind to all interfaces on your system.
This should give you the best chance of access.

You can use these commands to see what IPs you have to work with:
- Linux
  - `ip address show`
  - `ifconfig`
- Windows
  - `ipconfig`

Since you're using Azure - you may need to configure a public IP or use port forwarding for access from the internet.

**Comment by EmSi14** [comment]
Hello, sorry for "dropping" in on someone's issue, but its connected. I got past all the errors and I am stuck at the "docker: 'compose' is not a docker command". I update docker to v2.17.0 or am I missing something? I'm using ubuntu server 20.04. Thanks in advance and best regards, Martin

EDIT: Issue solved. Up and running. Thanks, a quite helpful tool.

**Comment by damionmounts** [comment]
@MartiniCv
No worries on you dropping-in on a related issue thread - glad you got it sorted out!

**Comment by fpsilva-source** [comment]
@MartiniCv 

Could you describe the steps taken to solve it?

**Comment by EmSi14** [comment]
@fpsilva-source 
Judging by the fact that you got the uWSGI up and running it's working. If the issue is accessing it, I'm still testing on different methods for https access (nginx/apache). If you followed Mr. Mounts' instructions and put it 0.0.0.0 for the WEB_IP variable, you should be able to access it via https://ip[.]address[.]ofVMorDevice:8001/ I tested it on a VM, set a static IP and thats it. A good practice would be, although there's nothing "valuable" that can be lost or stolen, to set up an admin account that is yours and then set a strong password for default admin and then do everything via you own admin account or even a user account. Does it work?

**Comment by fpsilva-source** [comment]
@MartiniCv thanks.
